FROM hashicorp/vault:latest

RUN apk add zsh git curl && \
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" && \
	touch $HOME/.zshrc && \
	vault -autocomplete-install

ENV VAULT_ADDR="http://vault-server:8200"
ENV VAULT_AGENT_CONFIG="/vautlt/config/agent.hcl"

COPY ./vault-agent-entrypoint.sh /usr/local/bin/vault-agent-entrypoint.sh
RUN chmod +x /usr/local/bin/vault-agent-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/vault-agent-entrypoint.sh"]
