/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TournamentScores } from "./TournamentScores";
export * as factories from "./factories";
export { TournamentScores__factory } from "./factories/TournamentScores__factory";
