#!/bin/bash

# Source the .env file generated by Vault

ENV_FILE=/tmp/env/.env

TRIES=20
echo "[entrypoint] Waiting for env file: $ENV_FILE"
while [ ! -f "$ENV_FILE" ] && [ $TRIES -gt 0 ]; do
  sleep 2
  TRIES=$((TRIES - 1))
done

set -o allexport;
set -a
if [ -f $ENV_FILE ]; then
  source $ENV_FILE
  . $ENV_FILE
fi
set +o allexport;
set +a

# Execute the original entrypoint with all arguments
exec /usr/local/bin/docker-entrypoint.sh "$@"
