services:

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:5173"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:3000
    networks:
      - backend
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ./docker/dockerfile
    container_name: backend
    ports:
      - "3001:3000"
    # env_file:
    #   - ./backend/Docker/.env
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./backend:/app
      - /app/node_modules # Exclure node_modules du montage pour utiliser ceux du conteneur
    # depends_on:
    #  - db
    
  vault:
    build:
      context: ./vault
      dockerfile: dockerfile
    container_name: vault-dev
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDRESS: "http://0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-dev-file:/vault/file
      - ./vault/config/vault.dev.hcl:/vault/config/vault.hcl:ro

networks:
  backend:
    driver: bridge

volumes:
  vault-dev-file:
