services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:3000
    networks:
      - backend
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ./docker/dockerfile
    container_name: backend
    ports:
      - "3001:3000"
    # env_file:
    #   - ./backend/Docker/.env
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - sqlite-data:/app/data
      # - ./vault/agent/:/app/.env:ro  # Use a named volume instead of bind mount
      - ./infra/vault/agent/env/:/app/env:rw


  vault-server:
    build:
      context: ./infra/vault/server
      dockerfile: dockerfile
    container_name: vault-server
    ports:
      - "8200:8200/tcp"
    cap_add:
      - IPC_LOCK
    volumes:
      # - ./vault/server:/vault/:rw

      - ./infra/vault/server/config:/vault/config:ro  # Config files as read-only
      - ./infra/vault/server/file:/vault/file:rw      # Only mount the storage directory
      - ./infra/vault/server/logs:/vault/logs:rw      # Mount logs directory
      - ./infra/vault/server/tokens/:/vault/tokens:rw           # Store tokens in a named volume
    restart: unless-stopped


  vault-agent:
    build:
      context: ./infra/vault/agent
      dockerfile: dockerfile
    container_name: vault-agent
    ports:
      - "8201:8200"
    depends_on:
      - vault-server
    volumes:
      - ./infra/vault/agent/config:/vault/config:ro   # Config files as read-only
      - ./infra/vault/agent/env/:/vault/env:rw                 # Write .env to a named volume
      - ./infra/vault/agent/logs:/vault/logs:rw       # Mount logs directory
      - ./infra/vault/server/tokens/:/vault/tokens:rw           # Read tokens from shared volume

    restart: unless-stopped


volumes:
  sqlite-data:
    

networks:
  backend:
    driver: bridge

