services:

  backend:
    build:
      context: ./backend
      dockerfile: ./docker/dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - sqlite-data:/app/data
      - ./vault/agent/.env:/app/.env:ro


  vault-server:
    build:
      context: ./vault/server
      dockerfile: dockerfile
    container_name: vault-server
    ports:
      - "8200:8200/tcp"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/server:/vault/:rw


  vault-agent:
    build:
      context: ./vault/agent
      dockerfile: dockerfile
    container_name: vault-agent
    ports:
      - "8201:8200"
    depends_on:
      - vault-server
    volumes:
      - ./vault/agent:/vault/:rw
      - ./vault/server/role_id:/vault/role_id:rw
      - ./vault/server/secret_id:/vault/secret_id:rw



volumes:
  sqlite-data:

networks:
  backend:
    driver: bridge

