services:

  backend:
    build:
      context: ./backend
      dockerfile: ./Docker/dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    # env_file:
    #   - ./backend/Docker/.env
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./backend:/app
    # depends_on:
    #  - db



networks:
  backend:
    driver: bridge


volumes:
  data:
