# include the compsoe of every provided type of service
include:
  - path: ./core/docker-compose.core.yml              # Core services (e.g., database, cache)
  - path: ./infra/vault/docker-compose.vault.yml            # Hashicorp Vault services
  # - path: ./infra/logging/docker-compose.logging.yml        # ELK stack services
  # - path: ./infra/monitoring/docker-compose.monitoring.yml  # Monitoring services


# Global network
networks:
  transcendence-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  escerts:
  esdata01:
  filebeatdata01:
  kibanadata:
  nginx_certs:
