services:

  backend:
    build:
      context: ./backend
      dockerfile: ./Docker/dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    # env_file:
    #   - ./backend/Docker/.env
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./backend:/app
    
  vault:
    build:
      context: ./vault/
      dockerfile: Dockerfile
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
    volumes:
      - ./vault/config/vault.prod.hcl:/vault/config/vault.hcl:ro
      - vault-prod-file:/vault/file

volumes:
  vault-dev-file:

networks:
  backend:
    driver: bridge

