services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - sqlite-data:/app/data   # Only this volume!

  vault:
    build:
      context: ./vault
      dockerfile: dockerfile
    container_name: vault-dev
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDRESS: "http://0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-dev-file:/vault/file
      - ./vault/config/vault.dev.hcl:/vault/config/vault.hcl:ro


volumes:
  vault-dev-file:
  sqlite-data:

networks:
  backend:
    driver: bridge

