services:

  vault-server:
    build:
      context: ./server
      dockerfile: dockerfile
    container_name: vault-server
    restart: unless-stopped
    ports:
      - "8200:8200/tcp"
    # expose: ["8200"]
    cap_add:
      - IPC_LOCK
    networks:
      - transcendence-network
    volumes:
      - ./server/config/:/vault/config:ro
      - ./server/ssl/:/vault/ssl:rw
      - ./server/logs/:/vault/logs:rw
      - ./server/tokens/:/vault/tokens:rw

  vault-agent:
    build:
      context: ./agent/
      dockerfile: dockerfile
    container_name: vault-agent
    restart: unless-stopped
    networks:
      - transcendence-network
    depends_on: 
      - vault-server
    ports:
      - "8201:8200"
    # expose: ["8201"]
    volumes:
      - ./agent/config/:/vault/config:ro
      - ./agent/logs/:/vault/logs:ro
      - ./server/tokens/:/vault/tokens:rw
      - ./agent/env/:/vault/env:rw
    healthcheck:
      test: ["CMD-SHELL", "test -f /vault/env/.env || exit 1"]
      interval: 1s
      timeout: 3s
      retries: 50
      start_period: 3s
