# Use Node.js 20 as the base image
FROM node:20

# Install pnpm
RUN corepack enable
RUN corepack prepare pnpm@latest --activate

# Set up PNPM environment
ENV PNPM_HOME=/root/.local/share/pnpm
ENV PATH=$PNPM_HOME:$PATH

# Install NestJS CLI globally
RUN pnpm install -g @nestjs/cli

# Set working directory
WORKDIR /app

# Copy package.json, pnpm-lock.yaml and other pnpm files
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install --frozen-lockfile

# Copy the rest of your application code
COPY . .

# Build the NestJS app
RUN pnpm run build

RUN cd node_modules/sqlite3 && \
	pnpm run rebuild 

# Expose port 3000
EXPOSE 3000

# Start the app
CMD ["pnpm", "run", "start:prod"]
