# Use Node.js 20 as the base image
FROM node:20

# Install pnpm globally
RUN corepack enable

# Set working directory
WORKDIR /app

# Copy package.json, pnpm-lock.yaml and other pnpm files
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install --frozen-lockfile

# Copy the rest of your application code
COPY . .

# Build the NestJS app
RUN pnpm run build

# Expose port 3000
EXPOSE 3000

# Start the app
CMD ["pnpm", "start"]
