FROM hashicorp/vault:latest

# Install zsh, git, curl, jq
RUN apk add zsh git curl jq && \
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || true && \
    touch $HOME/.zshrc && \
    vault -autocomplete-install

ENV VAULT_ADDR="http://vault-server:8200"

COPY ./vault-server-entrypoint.sh /usr/local/bin/vault-server-entrypoint.sh
RUN chmod +x /usr/local/bin/vault-server-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/vault-server-entrypoint.sh"]
